name: Kubernetes Manifests generation CI

on:
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: dciborow/action-pylint@0.1.0
      with:
        github_token: ${{ secrets.github_token }}
        # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
        reporter: github-pr-review
        level: warning
        glob_pattern: "*.py"
        pylint_args: "--max-line-length=120 --disable=C0114,C0115,C0116 --good-names=i,j,k,env,_ --ignore=tests"


    # - name: Install linter
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pylint

    # - name: Run pylint
    #   run: |
    #     pylint *.py \
    #       --disable=C0114,C0115,C0116 \
    #       --max-line-length=120 \
    #       --good-names=i,j,k,env,_ \
    #       --ignore=tests --output-format=text
    #   continue-on-error: true



  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt

    - name: Run tests and save manifest
      run: |
        mkdir -p test-results
        pytest --maxfail=1 --disable-warnings --json-report --json-report-file=test-results/manifest.json

    - name: Upload test manifest
      uses: actions/upload-artifact@v4
      with:
        name: test-manifest
        path: test-results/manifest.json